'use client';
import { useState, useEffect, useRef } from 'react';
import { Bot, Send, User2, Satellite, User, Rocket, Telescope, Microscope } from 'lucide-react';
import { cn } from '@/lib/utils';

// Comprehensive NASA Knowledge Base
const nasaKnowledgeBase = {
    artemis: {
        patterns: ["artemis", "moon mission", "lunar program", "return to moon"],
        response: `**Artemis Program** - NASA's mission to return humans to the Moon and establish sustainable exploration.

**Key Goals:**
• Land the first woman and first person of color on the Moon
• Establish long-term lunar exploration
• Test technologies for future Mars missions
• Build the Lunar Gateway space station

**Current Status:**
• Artemis I: Completed uncrewed test flight (2022)
• Artemis II: First crewed flight around Moon (planned 2025)
• Artemis III: Lunar landing mission (planned 2026)

**Technology:**
• Space Launch System (SLS) rocket
• Orion spacecraft
• Lunar Gateway station
• Commercial lunar landers

<div class="knowledge-source">Source: NASA Artemis Program Office</div>`
    },

    james_webb: {
        patterns: ["james webb", "webb telescope", "jwst", "space telescope"],
        response: `**James Webb Space Telescope** - NASA's premier infrared observatory.

**Key Capabilities:**
• Observes in infrared to see first galaxies
• 6.5-meter gold-coated primary mirror
• Sunshield size of a tennis court
• Operating at L2 Lagrange point

**Major Discoveries:**
• Earliest galaxies ever observed
• Detailed atmospheric studies of exoplanets
• Star formation in nearby galaxies
• Chemistry of distant planetary systems

**Recent Findings:**
• Carbon-based molecules in early universe
• Water vapor in planet-forming disks
• Complex organic molecules around young stars

<div class="knowledge-source">Source: NASA JWST Science Team</div>`
    },

    iss: {
        patterns: ["international space station", "iss", "space station"],
        response: `**International Space Station** - Orbiting laboratory and partnership achievement.

**Research Areas:**
• Human health in microgravity
• Materials science
• Earth and space observation
• Technology development
• Biology and biotechnology

**Recent Experiments:**
• Plant growth in space (Veggie system)
• Cancer research in microgravity
• 3D printing of human tissue
• Study of aging processes

**Partnership:**
• NASA (United States)
• Roscosmos (Russia)
• ESA (Europe)
• JAXA (Japan)
• CSA (Canada)

<div class="knowledge-source">Source: NASA ISS Program Office</div>`
    },

    mars: {
        patterns: ["mars", "red planet", "mars rover", "perseverance", "curiosity"],
        response: `**Mars Exploration Program** - NASA's ongoing investigation of the Red Planet.

**Current Rovers:**
• **Perseverance** - Searching for signs of ancient life, collecting samples
• **Curiosity** - Studying Martian climate and geology

**Key Discoveries:**
• Evidence of past water activity
• Organic molecules in rocks
• Seasonal methane variations
• Ancient river delta in Jezero Crater

**Future Missions:**
• Mars Sample Return campaign
• Human exploration planning
• MOXIE experiment producing oxygen from CO2

<div class="knowledge-source">Source: NASA Mars Exploration Program</div>`
    },

    rockets: {
        patterns: ["rocket", "sls", "space launch system", "how do rockets work"],
        response: `**Rocket Science & NASA's Launch Systems**

**Basic Principles:**
• Newton's Third Law - action/reaction
• Thrust generated by expelling mass
• Rocket equation governs performance

**NASA's Current Rockets:**
• **SLS** - Most powerful rocket ever built, for Artemis missions
• **Falcon** - Commercial crew missions to ISS
• **Atlas V** - Science missions and satellites

**Key Components:**
• Propellant tanks (liquid hydrogen/oxygen)
• Rocket engines (RS-25, Merlin, etc.)
• Guidance and navigation systems
• Payload fairings

<div class="knowledge-source">Source: NASA Engineering Directorate</div>`
    },

    technology: {
        patterns: ["nasa technology", "space technology", "inventions", "spinoff"],
        response: `**NASA Technology Transfer** - Innovations benefiting life on Earth.

**Medical Advances:**
• Digital imaging breast biopsy
• Artificial heart pumps
• Light-emitting diodes for wound healing
• Cochlear implants

**Public Safety:**
• Firefighting equipment
• Emergency response tools
• Water purification systems
• Radiation detection

**Consumer Products:**
• Memory foam mattresses
• Scratch-resistant lenses
• Athletic shoe designs
• Wireless headsets

**Environmental:**
• Solar cell technology
• Water recycling systems
• Air quality monitors
• Climate research tools

<div class="related-topics">
<strong>Related:</strong> Ask about specific NASA technologies like "spacesuit design" or "satellite technology"
</div>`
    },

    black_holes: {
        patterns: ["black hole", "event horizon", "singularity"],
        response: `**Black Hole Research** - NASA's study of these cosmic phenomena.

**Key NASA Missions:**
• **Chandra X-ray Observatory** - Studies high-energy regions
• **Hubble Space Telescope** - Observes effects on surroundings
• **NuSTAR** - Looks at high-energy X-rays
• **Swift** - Monitors gamma-ray bursts

**Recent Discoveries:**
• Supermassive black holes in galaxy centers
• Gravitational wave detection (with LIGO)
• Black hole mergers and growth
• Accretion disk physics

**Notable Findings:**
• First image of black hole shadow (Event Horizon Telescope)
• Measurements of black hole spin
• Study of relativistic jets
• Black hole feeding mechanisms

<div class="knowledge-source">Source: NASA Astrophysics Division</div>`
    },

    exoplanets: {
        patterns: ["exoplanet", "alien planet", "habitable zone", "kepler", "tess"],
        response: `**Exoplanet Research** - Search for planets beyond our solar system.

**NASA Missions:**
• **Kepler** - Found thousands of exoplanets
• **TESS** - Surveying nearby bright stars
• **James Webb** - Atmospheric characterization
• **Hubble** - Follow-up observations

**Key Discoveries:**
• Over 5,000 confirmed exoplanets
• Planets in habitable zones
• Variety of planet types
• Atmospheric composition studies

**Habitable Worlds:**
• TRAPPIST-1 system with Earth-sized planets
• Proxima Centauri b - nearest exoplanet
• Kepler-452b - "Earth's cousin"

<div class="knowledge-source">Source: NASA Exoplanet Exploration Program</div>`
    },

    earth_science: {
        patterns: ["earth science", "climate change", "global warming", "weather", "climate"],
        response: `**NASA Earth Science** - Studying our home planet from space.

**Key Satellites:**
• **Landsat** - Longest continuous space-based record of Earth's surface
• **GRACE** - Measures Earth's gravity field
• **ICESat** - Ice sheet elevation
• **Aqua/Terra** - Comprehensive Earth observation

**Research Areas:**
• Climate change monitoring
• Sea level rise
• Deforestation tracking
• Air quality assessment
• Natural disaster monitoring

**Recent Findings:**
• Accelerated ice melt in polar regions
• Changing precipitation patterns
• Urban heat island effects
• Ocean current changes

<div class="knowledge-source">Source: NASA Earth Science Division</div>`
    },

    careers: {
        patterns: ["career", "job", "internship", "work for nasa", "employment"],
        response: `**NASA Careers & Opportunities**

**Career Paths:**
• Engineering (aerospace, mechanical, electrical)
• Science (physics, astronomy, planetary science)
• Technology (software, data science, AI)
• Administration and support roles

**How to Apply:**
• USAJobs.gov for civil service positions
• Contractor positions through partner companies
• NASA Internships for students
• Pathways Program for recent graduates

**Educational Requirements:**
• STEM degrees typically required
• Advanced degrees for research positions
• Relevant experience and skills

**Internship Programs:**
• NASA Internships (all centers)
• NASA Community College Aerospace Scholars
• Minority University Research and Education Project

<div class="related-topics">
<strong>Learn More:</strong> Visit NASA.gov/careers or ask about specific NASA centers
</div>`
    },

    history: {
        patterns: ["nasa history", "when was nasa founded", "space race"],
        response: `**NASA History** - From inception to present.

**Key Dates:**
• 1958: NASA established by National Aeronautics and Space Act
• 1961: Alan Shepard - first American in space
• 1969: Apollo 11 - first Moon landing
• 1981: First Space Shuttle flight
• 1998: International Space Station assembly begins
• 2020: Commercial Crew Program begins

**Major Programs:**
• Mercury - First Americans in space
• Gemini - Spacecraft maneuvers and EVA
• Apollo - Moon landings
• Space Shuttle - Reusable spacecraft
• ISS - International cooperation

**Current Era:**
• Artemis - Return to Moon
• Commercial space partnerships
• Mars exploration
• Space technology development

<div class="knowledge-source">Source: NASA History Office</div>`
    }
};

const getCurrentTime = () => {
    const now = new Date();
    return now.getHours().toString().padStart(2, '0') + ':' +
           now.getMinutes().toString().padStart(2, '0');
};

const initialMessage = {
    role: 'assistant',
    text: `<strong>Welcome to NASA Research Assistant!</strong><br><br>
            I'm your comprehensive NASA knowledge resource. I can help you with:<br><br>
            
            • <span class="highlight">Mission Information</span> - Apollo, Artemis, ISS, Mars rovers, telescopes<br>
            • <span class="highlight">Scientific Research</span> - Astrophysics, planetary science, Earth science, biology<br>
            • <span class="highlight">Technology & Engineering</span> - Rockets, satellites, space suits, instruments<br>
            • <span class="highlight">Astronomy & Space Science</span> - Black holes, exoplanets, solar system<br>
            • <span class="highlight">NASA Programs</span> - Current and historical missions, research centers<br>
            • <span class="highlight">Career & Education</span> - Opportunities, internships, STEM programs<br><br>
            
            What would you like to know about NASA today?`,
    time: getCurrentTime()
};

const suggestions = [
    { question: "Tell me about the Artemis program", label: "🌙 Artemis Program" },
    { question: "What's new with the James Webb Telescope?", label: "🔭 James Webb" },
    { question: "How do rockets work?", label: "🚀 Rocket Science" },
    { question: "Latest Mars rover discoveries", label: "🔴 Mars Discoveries" },
    { question: "NASA career opportunities", label: "👨‍🚀 Careers at NASA" },
    { question: "International Space Station research", label: "🛰️ ISS Research" },
];

export default function AiResearchCopilotPage() {
    const [messages, setMessages] = useState([initialMessage]);
    const [inputValue, setInputValue] = useState('');
    const [isTyping, setIsTyping] = useState(false);
    const messagesEndRef = useRef<HTMLDivElement>(null);

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    };

    useEffect(() => {
        messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
    }, [messages, isTyping]);


    const handleSendMessage = () => {
        const trimmedInput = inputValue.trim();
        if (!trimmedInput) return;

        setMessages(prev => [...prev, { role: 'user', text: trimmedInput, time: getCurrentTime() }]);
        setInputValue('');
        setIsTyping(true);

        setTimeout(() => {
            const response = generateAIResponse(trimmedInput);
            setIsTyping(false);
            setMessages(prev => [...prev, { role: 'assistant', text: response, time: getCurrentTime() }]);
        }, 1000 + Math.random() * 1000);
    };
    
    const handleSuggestionClick = (question: string) => {
        setInputValue(question);
        setTimeout(() => document.getElementById('sendButton')?.click(), 0);
    };

    const generateAIResponse = (userMessage: string) => {
        const lowerMessage = userMessage.toLowerCase();
        
        for (const key in nasaKnowledgeBase) {
            const entry = nasaKnowledgeBase[key as keyof typeof nasaKnowledgeBase];
            for (const pattern of entry.patterns) {
                if (lowerMessage.includes(pattern)) {
                    return entry.response;
                }
            }
        }
        
        // Default response
        return `I understand you're asking about NASA-related topics. While I have comprehensive knowledge about many NASA subjects, I want to make sure I give you the most accurate information.

**I can help you with:**

<div class="related-topics">
<strong>Mission Information:</strong> Artemis, ISS, Mars rovers, telescopes<br>
<strong>Science Research:</strong> Astrophysics, planetary science, Earth science<br>
<strong>Technology:</strong> Rockets, satellites, space technology spinoffs<br>
<strong>Careers:</strong> Jobs, internships, educational opportunities<br>
<strong>History:</strong> Apollo program, Space Shuttle, NASA's founding
</div>

Could you please rephrase your question or be more specific about what NASA topic you'd like to learn about? I'm here to provide detailed, accurate information about all aspects of NASA's work and research.`;
    };

    return (
        <div className="flex justify-center items-center h-full bg-gradient-to-br from-[#0a1128] to-[#1a243d] p-4">
            <div className="w-full max-w-5xl h-[90vh] bg-[#1a243d]/95 rounded-2xl shadow-2xl border border-[#2d3a5c] flex flex-col overflow-hidden">
                <div className="bg-[#0b3d91]/90 p-6 text-center border-b border-[#2d3a5c]">
                    <h1 className="text-3xl font-bold mb-2 flex items-center justify-center gap-3">🚀 NASA Research Assistant</h1>
                    <p className="text-lg text-[#b8c2d6] max-w-2xl mx-auto leading-normal">Ask me anything about NASA missions, research, technology, astronomy, or space exploration.</p>
                </div>

                <div className="flex-1 p-6 overflow-y-auto space-y-5">
                    {messages.map((msg, index) => (
                        <div key={index} className={cn('flex gap-4 max-w-[90%] animate-[fadeIn_0.4s_ease-in]', msg.role === 'user' ? 'self-end flex-row-reverse' : 'self-start')}>
                            <div className={cn('w-11 h-11 rounded-full flex items-center justify-center font-bold flex-shrink-0 text-xl', msg.role === 'user' ? 'bg-[#fc3d21] shadow-[0_4px_12px_rgba(252,61,33,0.3)]' : 'bg-[#0b3d91] shadow-[0_4px_12px_rgba(11,61,145,0.3)]')}>
                                {msg.role === 'user' ? '👨‍🚀' : '🛰️'}
                            </div>
                            <div className={cn('bg-white/5 p-4 rounded-2xl backdrop-blur-md', msg.role === 'user' ? 'bg-gradient-to-br from-[#0b3d91] to-[#1e5bc9] rounded-tr-md shadow-[0_4px_15px_rgba(11,61,145,0.3)]' : 'rounded-tl-md')}>
                                <div className="text-base leading-relaxed whitespace-pre-wrap" dangerouslySetInnerHTML={{ __html: msg.text }} />
                                <p className="text-xs text-[#b8c2d6] mt-2 text-right">{msg.time}</p>
                            </div>
                        </div>
                    ))}
                    {isTyping && (
                         <div className="flex items-center gap-4 self-start">
                             <div className="w-11 h-11 rounded-full flex items-center justify-center font-bold flex-shrink-0 text-xl bg-[#0b3d91] shadow-[0_4px_12px_rgba(11,61,145,0.3)]">🛰️</div>
                            <div className="flex items-center gap-2 p-4 bg-white/5 rounded-2xl rounded-tl-md backdrop-blur-md">
                                <div className="w-2.5 h-2.5 rounded-full bg-[#b8c2d6] animate-[typing_1.4s_infinite_ease-in-out] [animation-delay:-0.32s]"></div>
                                <div className="w-2.5 h-2.5 rounded-full bg-[#b8c2d6] animate-[typing_1.4s_infinite_ease-in-out] [animation-delay:-0.16s]"></div>
                                <div className="w-2.5 h-2.5 rounded-full bg-[#b8c2d6] animate-[typing_1.4s_infinite_ease-in-out]"></div>
                                <span className="ml-2 text-[#b8c2d6] text-sm">NASA Assistant is researching...</span>
                            </div>
                         </div>
                    )}
                    <div ref={messagesEndRef} />
                </div>

                <div className="p-6 border-t border-[#2d3a5c] bg-[#1a243d]/80 backdrop-blur-md">
                    <div className="flex flex-wrap justify-center gap-3 mb-5">
                        {suggestions.map((suggestion, index) => (
                            <button
                                key={index}
                                onClick={() => handleSuggestionClick(suggestion.question)}
                                className="bg-[#0b3d91]/25 border border-[#2d3a5c] text-[#b8c2d6] px-5 py-3 rounded-full text-sm cursor-pointer transition-all hover:bg-[#0b3d91]/40 hover:text-white hover:-translate-y-0.5 shadow-md"
                            >
                                {suggestion.label}
                            </button>
                        ))}
                    </div>
                    <div className="flex gap-4 items-center">
                        <input
                            type="text"
                            id="userInput"
                            value={inputValue}
                            onChange={(e) => setInputValue(e.target.value)}
                            onKeyPress={(e) => e.key === 'Enter' && handleSendMessage()}
                            placeholder="Ask any NASA-related question..."
                            autoComplete="off"
                            className="flex-1 px-6 py-4 bg-white/10 border border-[#2d3a5c] rounded-full text-white placeholder:text-[#b8c2d6] focus:outline-none focus:border-[#0b3d91] focus:bg-white/15 focus:ring-2 focus:ring-[#0b3d91]/50 transition-all"
                        />
                        <button
                            id="sendButton"
                            onClick={handleSendMessage}
                            className="w-14 h-14 rounded-full bg-gradient-to-br from-[#0b3d91] to-[#1e5bc9] text-white flex items-center justify-center transition-all hover:from-[#1e5bc9] hover:to-[#2a6de6] hover:scale-105 hover:shadow-lg hover:shadow-[#0b3d91]/40 active:scale-95"
                        >
                            <Send size={22} />
                        </button>
                    </div>
                </div>
            </div>
            <style jsx global>{`
                @keyframes fadeIn {
                    from { opacity: 0; transform: translateY(15px) scale(0.95); }
                    to { opacity: 1; transform: translateY(0) scale(1); }
                }
                @keyframes typing {
                    0%, 80%, 100% { transform: scale(0.8); opacity: 0.5; }
                    40% { transform: scale(1); opacity: 1; }
                }
                .knowledge-source {
                    background: rgba(26, 147, 111, 0.15);
                    border-left: 4px solid #1a936f;
                    padding: 12px 16px;
                    margin: 12px 0;
                    border-radius: 0 8px 8px 0;
                    font-size: 0.85rem;
                }
                .related-topics {
                    background: rgba(255, 193, 7, 0.1);
                    border: 1px solid rgba(255, 193, 7, 0.3);
                    padding: 15px;
                    margin: 15px 0;
                    border-radius: 10px;
                    font-size: 0.9rem;
                }
                .highlight {
                    background: rgba(255, 193, 7, 0.2);
                    padding: 2px 6px;
                    border-radius: 4px;
                    font-weight: 600;
                }
            `}</style>
        </div>
    );
}
